### ISSUE TITLE
OnSubscribeSharedPreferenceChange does not notify the subscriber on preference change

### ISSUE THREAD

**Issue by lungos** [ReactiveX/RxAndroid#125]
This is the current workflow of `OnSubscribeSharedPreferenceChange`
(a) On subscribe, it registers an anonymous class as a listener of the shared preferences. 
(b) On preference change, It notifies the the subscriber that the given preference changed. 

- `SharedPreferences` only hold a weak reference to the listeners.
- `OnSubscribeSharedPreferenceChange` does not retain the listener. 

Considering that, it is very likely that listener will be garbage collected between (a) and (b) and that the subscriber will not be receive the preference changes. 

One solution would be to retain the listener as a field of the `OnSubscribeSharedPreferenceChange`, the caller would have to retain the `Observable` or the `Subscription` to avoid garbage collection after `OnSubscribeSharedPreferenceChange.call()` was called. Any thoughts ? 

cc @omo @jdamcd @mttkay

**Comment by ronshapiro** [comment]
[This anonymous class](https://github.com/ReactiveX/RxAndroid/blob/8ba5c40c98147b5799ea55bbb22c1eebe34fea70/rxandroid/src/main/java/rx/android/content/OnSubscribeSharedPreferenceChange.java#L39-L44) should be retaining the reference to `listener` until `Observable.unsubscribe()` is called since it's connected via the result of `Subscriptions.create()`, no? If not, we could make the `OnSubscribe` hold a reference and `null` it out on `unsubscribe`. Not sure the best way to confirm this is an issue/writing a test around this, but it would be nice to have if possible. Calling `System.gc()` is not reliable AFAICT. Does anyone have any experience testing `WeakReference`?

**Comment by mttkay** [comment]
The listener is a method local reference, which is captured only by the argument, which is the downstream subscriber. If you invoke that observable with another method local subscriber, then unless you hold a strong reference to the observable or a strong reference to the subscription, everything gets GC'ed.

I think what the problem was is that we didn't hold on to either the observable or the subscription (correct me if wrong @lungos )

**Comment by lungos** [comment]
Yes. The subscription keep a reference to the listener, so keeping a reference to the subscription would prevent the listener from being garbage collected. 

I don't think keeping a reference to the observable would have any effect, though. The observable does not keep a reference to the listener. 

My only concern is, but you're right it is specific to each implementation, most of the time we do not need to unsubscribe since we want to listen to preference changes all the time. Then, it is not natural to hold a reference to the subscription. And if the subscription is unused it may be removed by proguard... (then, the gc would collect it)

I guess what I am saying is that it is not very natural to use correctly this guy. I am not sure any more it is a good idea to have it.
