### ISSUE TITLE
Missing support ReactiveDialog

### ISSUE THREAD

**Issue by liminal** [ReactiveX/RxAndroid#141]
Is there a reason other than not having got around to it that there's an `rx.android.app.ReactiveDialog` but no `rx.android.app.support.ReactiveDialog` ?

**Comment by JakeWharton** [comment]
Send a PR!

**Comment by liminal** [comment]
I'd love to but I'm currently stuck with the #133 bug and can't even open the project. Looks like @prt2121 managed to do it though.

**Comment by JakeWharton** [comment]
ReactiveDialog has been removed as part of the efforts of #172. Dialogs are simply too broad of a use case to solve in a good way for everyone. There's far too many use cases and feature requests.

**Comment by ashughes** [comment]
Is ReactiveDialog now maintained in a separate project somewhere?

**Comment by djensen47** [comment]
It does not appear to have been moved.

**Comment by djensen47** [comment]
It looks like @dlew was involved in creating ReactiveDialog. Any chance he can maintain it?

**Comment by prt2121** [comment]
@djensen47 have you seen @dlew's comments at https://github.com/JakeWharton/RxBinding/issues/32?

**Comment by djensen47** [comment]
Thanks. Sometimes it's a needle/haystack problem navigating GitHub issues. :smile:

**Comment by dlew** [comment]
For the record: I was not involved in the creation of ReactiveDialog (besides maybe some discussion on the PR), nor have I ever used it.

**Comment by djensen47** [comment]
Okay, sorry, I guess I read the commits upside down.

**Comment by djensen47** [comment]
Yeah, it looks like @Dorvaryn was involved in the initial ReactiveDialog?

**Comment by Dorvaryn** [comment]
@djensen47 @ashughes ReactiveDialog is no longuer being maintained. It is quite difficult to make something generic enough to work in most cases and since we pulled away at Novoda from using Rx in UI layer we didn't put too much effort into it. ReactiveDialog was not suppose to work on it's own as there is also a need for a way to retain observables over rotation if you want to take full advantage of it. The component was not that complex anyway, I would advise you to implement it yourself if you need it, it will probably a better fit than this.

**Comment by ashughes** [comment]
@Dorvaryn Thanks for the update. I posted a SO question about this: http://stackoverflow.com/q/32418282/287575 If anyone has any suggestions or best practices for this, it would be greatly appreciated.
