### ISSUE TITLE
onNext not called if onError is called immediately after when Scheduler is defined in observeOn

### ISSUE THREAD

**Issue by mariusgreve** [ReactiveX/RxAndroid#155]
If I set a `Scheduler` in `.observeOn(...)` for an `Observable` and call `subscriber.onError` immediately after `subscriber.onNext`, `onNext` is never called in my `Observer`.

If I either add a sleep between `subscriber.onNext` and `subscriber.onError` or don't set a `Scheduler` in `.observeOn(...)`, `onNext` is called in my `Observer`.

See example:

```java
Observable.create(new Observable.OnSubscribe<String>() {
	@Override
	public void call(Subscriber<? super String> subscriber) {
		subscriber.onNext("Test");
		subscriber.onError(null);
	}
}).observeOn(AndroidSchedulers.mainThread())
		.subscribe(new Observer<String>() {
			@Override
			public void onCompleted() {
				System.out.println("onCompleted");
			}

			@Override
			public void onError(Throwable e) {
				System.out.println("onError");
			}

			@Override
			public void onNext(String s) {
				System.out.println("onNext");
			}
		});

// Only prints "onError", but should print "onNext" and then "onError"
```

**Comment by JakeWharton** [comment]
This is true of vanilla RxJava. Not an RxAndroid problem. Either ask on the RxJava mailing list or file an issue on the RxJava project.

**Comment by mariusgreve** [comment]
Sorry, my bad. I was actually gonna post it on the RxJava project. Had the wrong window open

**Comment by mttkay** [comment]
This is interesting. Could you backlink the issue here?

I think the reason this is happening is because `onError` is a terminal state, and `DefaultSubscriber` unsubscribes itself in terminal states. What I imagine might be happening is that unsubscribing happens before the operator gets a change to deliver the `next` notification (although you call them in succession, they will do a round trip through Android's message loop.)

That said, this may or may not be a problem with RxJava core.

**Comment by JakeWharton** [comment]
https://github.com/ReactiveX/RxJava/issues/2887

**Comment by mttkay** [comment]
:+1:
