### ISSUE TITLE
UI does not update after usage of `toSortedList( sortFunction )`

### ISSUE THREAD

**Issue by osamarao** [ReactiveX/RxAndroid#181]
While getting an `ArrayList` from an api via `Retrofit`, the subscriber does not update any UI components in `onSubscribe`, `toSortedList( sortFunction )` is used. 

The Subscriber does not receive any event and hence no UI components are updated.

Here's my use case.

    .flatMap(new Func1<String, Observable<ArrayList<Places>>>() {
        @Override
        public Observable<ArrayList<Places>> call(String s) {
            return placesApi.suggest("en", s);
        }
    })
    .flatMap(new Func1<ArrayList<Places>, Observable<Places>>() {
        @Override
        public Observable<Places> call(ArrayList<Places> placeses) {
            return Observable.from(placeses);
        }
    })
    .toSortedList(new Func2<Places, Places, Integer>() {
        @Override
        public Integer call(Places place1, Places place2) {
            return comparePlaces(place1, place2);
        }
    })

**Comment by plastiv** [comment]
`toSortedList` will wait for the `onComplete` event of the whole sequence. In your case `onComplete` is not triggered by `searchObservable` since it waits forever for the user input. You have to make next update.

```
.flatMap(new Func1<ArrayList<Places>, Observable<List<Places>>>() {
    @Override
    public Observable<List<Places>> call(ArrayList<Places> placeses) {
        return Observable.from(placeses)
                           .toSortedList(new Func2<Places, Places, Integer>() {
                               @Override
                               public Integer call(Places place1, Places place2) {
                                  return comparePlaces(place1, place2);
                               }
                           });
    }
})

```
So for this particular case using Reactive is pointless because you can use `Collections.sort` instead.

Anyway, this question has nothing to do with the project and should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rx-java).

**Comment by osamarao** [comment]
I see. I thought it was a bug with the library, since the documentation for `toSortedList()` did not mention these caveats. Thank you for clearing this out for me.
