### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxAndroid#185]
What is needed to be considered v1.0?

**Comment by JakeWharton** [comment]
Current plan is to gut the library (#172) with a focused core that we can 1.0. Everything else in here is a mess, inconsistent, and questionably useful to the masses.

**Comment by mttkay** [comment]
Have you chatted to Erik yet? Apparently he’s working on a leaner, more
mobile friendly flavor of RxJava:
https://twitter.com/headinthebox/status/606812611313864704

Just to make sure we don’t create unnecessary fragmentation.

On Mon, Jun 29, 2015 at 6:05 PM, Jake Wharton <notifications@github.com>
wrote:

> Current plan is to gut the library (#172
> <https://github.com/ReactiveX/RxAndroid/issues/172>) with a focused core
> that we can 1.0. Everything else in here is a mess, inconsistent, and
> questionably useful to the masses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxAndroid/issues/185#issuecomment-116743586>
> .
>



-- 

Matthias Käppler

*Engineer*


Twitter: https://twitter.com/mttkay

Skype: matthias-sc



SoundCloud Ltd. | Rheinsberger Str. 76/77, 10115 Berlin, Germany | +49
(0)172 2345679

Managing Director: Alexander Ljung | Incorporated in England & Wales
with Company
No. 6343600 | Local Branch Office | AG Charlottenburg  | HRB 110657B



Capture and share your music & audio on SoundCloud
<http://soundcloud.com/creators>

**Comment by benjchristensen** [comment]
> Current plan is to gut the library

Should the current code be considered 1.0 and all of what #172 be done as 2.0?

> working on a leaner, more mobile friendly flavor of RxJava

Note that it is not open source. It's a commercial offering.

**Comment by headinthebox** [comment]
We are doing a super lightweight RxJava implementation optimized for mobile & UI scenarios (amongst other things it removes 90 operators that either nobody uses, or that can easily be expressed in terms of other operators). 

The API surface is largely backwards compatible; main differences are that we are using Java Streams instead of RxJava method names if applicable, the scheduler interface more like `ScheduledExecutorService`, and by design we do not support back pressure (none of the Android sources we bind supports back-pressure, and it greatly reduces the complexity of the implementation). 

So it should be easy to use with a new and improved RxAndroid (which I agree is ready for a reboot).

**Comment by headinthebox** [comment]
> Note that it is not open source. It's a commercial offering.

Just want to point out that is possible to be both a commercial offering *and* open source.

**Comment by dlew** [comment]
> Should the current code be considered 1.0 and all of what #172 be done as 2.0?

I would vote against just because I don't consider the current code to be stable. It's still feels like a WIP.

**Comment by JakeWharton** [comment]
It also potentially implies some sort of support for the code which I don't think anyone active on the project really wants.

**Comment by austynmahoney** [comment]
Can we put some kind of warning on the README for anyone coming along late to the party? I would hate for someone to implement the current version just to have it all deprecated.

**Comment by benjchristensen** [comment]
@dlew @JakeWharton makes sense, thanks for the explanation

**Comment by JakeWharton** [comment]
https://github.com/ReactiveX/RxAndroid/releases/tag/v1.0.0
