### ISSUE TITLE
question about to common error handle

### ISSUE THREAD

**Issue by xk009** [ReactiveX/RxAndroid#202]
Dear, author. I want to use your rxandroid  instand to request network。Like this 
        AppObservable.bindActivity(this, getRestClient().getUserService().getCode("18700001003"))
                .subscribe(codeBean -> {},
                error -> {
                    // error handle
                });
Question comes, I want to do some common error handle, like user token is invalid, should always tick out account。The ugly way is use same code in the every subscribe。Obviously, It is not suitable。 
Also, i can't  intrude  super class  do some common error handle。 
Please tell me  how to selove it。

**Comment by JakeWharton** [comment]
This is a general design question and really has nothing to do wtih RxJava or RxAndroid which is simply the mechanism you are using. Common solutions include base classes for your subscribers, wrapping your API client, or using `transform` with a common handler. I'm not going to go into details on these approaches since this is not a support forum. Please use the RxJava mailing list or StackOverflow for usage questions. This issue tracker is for bugs and feature requests only.
