### ISSUE TITLE
Add a proguard file for sample app.

### ISSUE THREAD

**Issue by dlew** [ReactiveX/RxAndroid#219]
RxJava includes some aspects that can cause problems w/ proguard: https://github.com/ReactiveX/RxJava/issues/3097

However, since it's just a JAR, it cannot itself include proguard protections. I think we should add some reasonable default protections to RxAndroid instead (even though we're not directly the source of it).

**Comment by mttkay** [comment]
There was some discussion in the past around making RxAndroid (or parts of
it) an AAR. You can ship default ProGuard rules with AARs, I think the play
services libraries do that.

Is that an option?

On Tue, Aug 25, 2015 at 4:22 PM, Daniel Lew <notifications@github.com>
wrote:

> RxJava includes some aspects that can cause problems w/ proguard:
> ReactiveX/RxJava#3097 <https://github.com/ReactiveX/RxJava/issues/3097>
>
> However, since it's just a JAR, it cannot itself include proguard
> protections. I think we should add some reasonable default protections to
> RxAndroid instead (even though we're not directly the source of it).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/RxAndroid/issues/219>.
>



-- 

Matthias Käppler

*Engineer*


Twitter: https://twitter.com/mttkay

Skype: matthias-sc



SoundCloud Ltd. | Rheinsberger Str. 76/77, 10115 Berlin, Germany | +49
(0)172 2345679

Managing Director: Alexander Ljung | Incorporated in England & Wales
with Company
No. 6343600 | Local Branch Office | AG Charlottenburg  | HRB 110657B



Capture and share your music & audio on SoundCloud
<http://soundcloud.com/creators>

**Comment by JakeWharton** [comment]
We're an aar now! I believe that's what Dan is referring to.

**Comment by dlew** [comment]
Yup, that's exactly what I'm interested in doing.

**Comment by artem-zinnatullin** [comment]
Just baked ProGuard rules for RxJava as a separate project (aar) https://github.com/artem-zinnatullin/RxJavaProGuardRules!

In plans: run all RxJava's tests on Android with these ProGuard rules to cover as max cases as possible! Not all of them compilable with Android SDK, so it will require some changes. 

P.S.

I don't think that RxAndroid should ship ProGuard rules for RxJava because there is no direct correlation between the version of RxAndroid and RxJava.

**Comment by jaredsburrows** [comment]
+1

**Comment by hzsweers** [comment]
This can be closed now after the decision in #220 right?

**Comment by stkent** [comment]
@JakeWharton @hzsweers I believe that this issue was repurposed by Jake on December 9th, _after_ the discussion in #220, and thus should remain open. (In general, it's probably better to close the issue/open a new one rather than repurpose an issue; I made this same mistake myself earlier!) The discussion and decision in #220 refers to the _original_ intent of this issue, which was to provide ProGuard rules embedded in the RxAndroid AAR.

**Comment by ityulong** [comment]
thank you!
