### ISSUE TITLE
ScalarSynchronousObservable cannot be cast to android.util.Pair

### ISSUE THREAD

**Issue by cesards** [ReactiveX/RxAndroid#230]
Hi!

I'm having an issue trying to use a Subscriber using the [Pair](http://developer.android.com/intl/ko/reference/android/util/Pair.html) android class.

The error I get is:
```java
java.lang.ClassCastException: rx.internal.util.ScalarSynchronousObservable cannot be cast to android.util.Pair
```
I could understand, RxAndroid comes from Rxjava and [Pair](http://developer.android.com/intl/ko/reference/android/util/Pair.html) casting hasn't been supported yet. Am I right?

Here are the code snippets:

1 - Subscriber for the use case I'm executing.
```java
private class TourStepListSubscriber extends Subscriber<Pair<List<TourStepEntity>, List<TeamEntity>>> {

    private final WorldTour worldTour;

    public TourStepListSubscriber(WorldTour worldTour) {
        this.worldTour = worldTour;
    }

    @Override
    public void onCompleted() {
        viewState.onNext(ViewState.COMPLETED);
    }

    @Override
    public void onError(Throwable e) {
        viewState.onNext(ViewState.ERROR);
    }

    @Override
    public void onNext(Pair<List<TourStepEntity>, List<TeamEntity>> listListPair) {
        viewState.onNext(ViewState.SUCCESS);
    }
}
```

2 - From my ViewModel, I'm executing the Use Case
```java
public void getSteps(WorldTour worldTour) {
    viewState.onNext(ViewState.LOADING);

    getTourStepsUseCase.execute(new TourStepListSubscriber(worldTour));
}
```

3 - Use Case executor
```java
/**
 * Executes the current use case.
 *
 * @param UseCaseSubscriber The guy who will be listen to the observable build with {@link #buildUseCaseObservable()}.
 */
@SuppressWarnings("unchecked")
public void execute(Subscriber UseCaseSubscriber) {
    this.subscription = this.buildUseCaseObservable()
            .subscribeOn(Schedulers.from(threadExecutor))
            .observeOn(postExecutionThread.getScheduler())
            .subscribe(UseCaseSubscriber);
}
```

4 - This is what I'm returning
```java
@Override
protected Observable buildUseCaseObservable() {
    final Observable<List<TourStepEntity>> stepsObservable = worldTourRepository
            .worldTourSteps(steps);

    final Observable<List<TeamEntity>> teamsObservable = stepsObservable
            .map(this::getTeamIds)
            .flatMap(teamRepository::teams);

    return Observable.zip(stepsObservable, teamsObservable, (tourStepEntities, teamEntities) -> {
        return Observable.just(new Pair<>(tourStepEntities, teamEntities)); // Error returning this
    });
}
```

If you need anything else. Just ask ^^

**Comment by JakeWharton** [comment]
`Observable.zip` [for combining two observables][1] takes a `Func2<T1, T2, R>` and has a single method with the signature `R call(T1 t1, T2 t2)`.

For your example, this becomes `Func2<List<TourStepEntity>>, List<TeamEntity>>, Object>` (note the return type is incorrectly `Object`). This is because the return type of `buildUseCaseObservable` uses the raw type `Observable` instead of a correctly parameterized version. Because there's no generic type, javac infers the widest bound possible for the generic, `Object`, and applies that through the `return` statement onto the `R` type variable of the `call` and thus the `Func2`. This allows _any_ object to be returned from the method, despite not being what you want.

To correct this, you should specify the correct return type on `buildUseCaseObservable`, `Observable<Pair<List<TourStepEntity>, List<TeamEntity>>>`, which will propagate up the same way and apply the correct generic to the `Func2`.

After doing this, you will see a compile error. That's because the return type of the `Func2`'s `call` has become `Pair<List<TourStepEntity>, List<TeamEntity>>`. An `Observable<Pair<List<TourStepEntity>, List<TeamEntity>>>` is not a `Pair<List<TourStepEntity>, List<TeamEntity>>` and thus it fails. This also shows where the cast exception was coming from. `Observable.just` returns a special instance of `Observable` which only knows how to emit one item. That class is called `ScalarSynchronousObservable`. Now that the problem has been moved into the type system and become a compilation issue, you can see that you need to remove the `Observable.just` wrapper around the `Pair` creation.

 [1]: http://reactivex.io/RxJava/javadoc/rx/Observable.html#zip(rx.Observable,%20rx.Observable,%20rx.functions.Func2)

**Comment by cesards** [comment]
Yep. Totally right. Would you use Generics as a contract in order to avoid this kind of misunderstandings? I've been using RxJava for 3 months but sometimes I become a mess with some of the operators.

Problem here is that communication between presentation and domain layer should be transparent. 

So the UseCase base class would be something like:
```java
public abstract class UseCase<T> {
    ...
    protected abstract Observable<T> buildUseCaseObservable();

    @SuppressWarnings("unchecked")
    public void execute(Subscriber UseCaseSubscriber) {
        this.subscription = this.buildUseCaseObservable()
                .subscribeOn(Schedulers.from(threadExecutor))
                .observeOn(postExecutionThread.getScheduler())
                .subscribe(UseCaseSubscriber);
    }
   ...
}

and the Specific Use Case:
```java
public class GetWorldTourSteps extends UseCase<Pair<List<TourStepEntity>, List<TeamEntity>>> {
    ...
    @Override
    protected Observable<Pair<List<TourStepEntity>, List<TeamEntity>>> buildUseCaseObservable() {
        final Observable<List<TourStepEntity>> stepsObservable = worldTourRepository
                .worldTourSteps(steps);

        final Observable<List<TeamEntity>> teamsObservable = stepsObservable
                .map(this::getTeamIds)
                .flatMap(teamRepository::teams);

        return Observable.zip(stepsObservable, teamsObservable, Pair::new);
    }
    ...
}
```

I know this is nothing to do with RxJava, I just was wondering if this would help in this case or is helpless anyway. It's a little bit ugly but I don't know if it's necessary dealing with this in order to avoid this kind of errors. Thank you so much in advance, your answer was quite declarative.

**Comment by JakeWharton** [comment]
I think ideally you would use generics, yes. I don't know enough about what you're doing to really understand what's going on, but there's not really any other way to push the guarantees that the types are correct into the compiler instead of happening at runtime. Ideally you would also use a generic for the `execute` method parameter: `Subscriber<? extends T>`.
