### ISSUE TITLE
AndroidSchedulers.mainThread()  can only do subscribe once

### ISSUE THREAD

**Issue by gao117348222** [ReactiveX/RxAndroid#248]
here is code
```android
    public void rxandroidtest(View v)
    {
        myObservable.observeOn(AndroidSchedulers.mainThread()).subscribe(mySubscriber);
    }
    rx.Observable<String> myObservable=rx.Observable.create(
            new rx.Observable.OnSubscribe<String>() {
                @Override
                public void call(Subscriber<? super String> subscriber) {
                    String webdata="testabc123";
                    subscriber.onNext(webdata);
                    subscriber.onCompleted();
                }
            }
    );
      Subscriber<String> mySubscriber=new Subscriber<String>() {
        @Override
        public void onStart() {
            e("onStart");
        }

    @Override
        public void onCompleted() {
            e("onCompleted");
        }

        @Override
        public void onError(Throwable e) {
            e("onError"+e);
        }

        @Override
        public void onNext(String s) {
            e(s);
        }
    };
    public void e(String s)
    {
        Log.e(TAG,s);
    }
```
this code,click button first time,log is ok:
onStart
testabc123
onCompleted

but click second time,the log is only
onStart

So,Is my code write wrong,or is a bug of rxAndroid?

**Comment by artem-zinnatullin** [comment]
It's not a problem of RxAndroid. 

It's a problem of reusing `Subscriber`. `Subscriber` has a state `isUnsubscribed` so it's a really bad idea to subscribe one `subscriber` to multiple `Observable`s because once it unsubscribed from one of the `Observable`s it will be broken for other `Observable`s.

First solution is to create new subscriber each time you want to subscribe to an `Observable`. Second solution is to subscribe not the `Subscriber`, but the `Observer` but anyway, reusing such entities is a sign that you're doing something wrong, so I'd suggest using first solution.

Hope your issue is resolved and could be closed.

**Comment by artem-zinnatullin** [comment]
:+1:

**Comment by mttkay** [comment]
It’s interesting to note that in the original Rx.NET implementation,
Subscribers are called Disposables. They’re not meant to be reused (by
design.)

**Comment by artem-zinnatullin** [comment]
Yeah, though we can enforce same behavior in RxJava via throwing exception in `subscribe(subscriber)` if `subscriber` already `subscribed` somewhere (but probably I'm missing some legal use-case here).

// off-topic
RxJava has many design problems (though I like it a lot anyway) and the fact that Java 9 will have Flow API which is basically `SHIFT + F6` `Observable -> Flow` makes me sad. Because as a library RxJava can be changed/fixed pretty fast but as part of JDK we will see new features only in new JDK releases and fixes will be available only in particular versions of JRE and I'm pretty sure that Flow won't be perfect right from the release… JDK is already a mess of not very great concurrency APIs and in each major JDK release they add more and more of them :(
