### ISSUE TITLE
Is interval a replacement to Alarm?

### ISSUE THREAD

**Issue by cgcgbcbc** [ReactiveX/RxAndroid#257]
Traditionally a scheduled background task is implemented using Alarm Manager and Broadcast Receiver. Is rx.interval an alternative for this? And how about battery usage?

**Comment by dlew** [comment]
No, it's not a replacement. Interval is active code, whereas AM and BR wakes up the app.

Closing because this isn't about RxAndroid (interval is part of RxJava) and this forum is for bugs/features with the library. I suggest trying [StackOverflow](http://stackoverflow.com/) or similar to find answers in the future.
