### ISSUE TITLE
Catch when there are now changes in emitted data

### ISSUE THREAD

**Issue by vanjavanjavanja** [ReactiveX/RxAndroid#289]
Hi!

Here I'm observing changes in TextView `value t`:
```
Observable<CharSequence> observable = RxTextView.textChanges(t).skip(1);
        Subscription subscription = 
                observable.doOnNext(count ->
                {
                    Log.v("CLICKER", "count: " + count);
                }
        )
                .subscribe(count -> {
                });
```
and I need to start playing an audio `startAudio()` just in a couple of seconds after `t` started to change and stop playing `stopAudio()` it when `t` has stopped to be changing for another pair of secs.

Is there any suitable operators or what is the right direction to implement the described requirements?

**Comment by JakeWharton** [comment]
Hi @vanjavanjavanja,

GitHub issues are not a great place for support because it doesn't reach most of the right people who would be able to provide assistance and you question isn't really specific to anything about RxAndroid but more general RxJava usage. Can you ask your question on StackOverflow with the `rx-java` and `rx-android` tags? Or maybe post to the RxJava mailing list instead?

**Comment by vanjavanjavanja** [comment]
Very nice, thanks! 
> For bugs, feature requests, and **discussion** please use GitHub Issues.

**Comment by dlew** [comment]
"Discussion" is for the development/maintenance of the project itself. E.g., check out #172.
