### ISSUE TITLE
InterruptedIOException when switching from mainThread() to io() with Completable

### ISSUE THREAD

**Issue by tasegula** [ReactiveX/RxAndroid#322]
There seems to be a problem when switching from `AndroidSchedulers.mainThread()` to `Schedulers.io()` when chained on a `Completable`.

An `InterruptedIOException` is thrown when executing an OkHttp request.

```
private static final String URL = "https://www.google.ro/";

private Single<Integer> fetchData() {
    return Single.defer(new Callable<Single<Integer>>() {
        @Override
        public Single<Integer> call() throws Exception {        
            // get interrupted flag (log it) - always false
            boolean interrupted = Thread.interrupted();

            try {
                Request request = new Request.Builder()
                        .get().url(URL).build();

                // exception is thrown here
                Response response = mHttpClient.newCall(request).execute();
                return Single.just(response.code());
            } catch (IOException e) {
                return Single.error(e);
            }
        }
    });
}

public Completable withCompletable() {
    return Completable.complete() // usually does stuff
            .subscribeOn(AndroidSchedulers.mainThread())
            .observeOn(Schedulers.io())
            .andThen(fetchData())
            .toCompletable();
}

// Same with Single instead of Observable
public Observable<Integer> withObservable() {
    return Observable.just(10) // usually does stuff
            .subscribeOn(AndroidSchedulers.mainThread())
            .observeOn(Schedulers.io())
            .flatMap(new Func1<Integer, Observable<Integer>>() {
                @Override
                public Observable<Integer> call(Integer integer) {
                    return fetchData().toObservable();
                }
            });
}
```

What's the problem:
- If I'm calling `withCompletable()`, I get the exception 1 out of 10 times on Android API 19, and 9/10 on API 16.
- If I'm calling `withObservable()` or `withSingle()`, it works as expected.
- This also happens with Retrofit.

What works:
- If instead of `AndroidSchedulers.mainThread()`, I use `Schedulers.computation()`, it works with `Completable` too.
- If before the `andThen()` I add a `toSingle()` or `toSingleDefault()`, it works as expected.
- If in `fetchData()` I'm not doing any network request, it works as expected.

I've also added a [SO question](http://stackoverflow.com/questions/39137808/interruptedioexception-when-switching-from-mainthread-to-io?noredirect=1#comment65627792_39137808) when I encountered the problem.

3rd party versions:
- RxJava: 1.1.9
- RxAndroid: 1.2.1
- OkHttp: 3.4.1

**Comment by JakeWharton** [comment]
This makes sense to me. I don't think there's any action to take.

RxJava's `io()` is a pool of threads dedicated to running RxJava messages. So when you cancel a `Worker` from the `io()` `Scheduler` it interrupts the thread to try and kill the work as soon as possible. Once it recovers the thread from the task finishing it can re-use the thread whose interrupt flag has been cleared.

For Android, `mainThread()` wraps the main looper which is looping on a single thread we don't control and processing messages from the entire app. When you cancel a `Worker` from the `mainThread()` `Scheduler` we ask the `Handler` to remove all scheduled work. We don't do anything to work that's currently running because we can't verify that our message is currently running vs. some other random message processing input, running the activity lifecycle, etc.

**Comment by JakeWharton** [comment]
I guess you're not canceling the subscription though and that's the point? Still have trouble seeing how this library would be related.

Are you sure it just isn't a timeout exception being thrown from a slow request? Paste the full stacktrace.
