### ISSUE TITLE
Pinning with RxAndroid

### ISSUE THREAD

**Issue by 29unzz** [ReactiveX/RxAndroid#397]
For security reason in my app, i did implement SSL Pinning when networking using Okhttp.
My Scenario is simple by put wrong value for sha256.
With this sample code : 
```
CertificatePinner certPinner = new CertificatePinner.Builder().add("myown_hostname", "**sha256/4hw5tz+scE+TW+mlai5YipDfFWn1dqvfLG+nU7tq1V8=**").build();

OkHttpClient client = new OkHttpClient.Builder().certificatePinner(certPinner).build();
client.newCall(request);
Response response = mCall.execute();
```
Usually i got catch exception and the message as below : 
"**javax.net.ssl.SSLPeerUnverifiedException**"

Now when combine with **RxAndroid**. Im running test with same scenario, nothing happenned.
**No exception catch**. So this is piece of code using RxAndroid:

This is my **NetworkService.java** : 
```
CertificatePinner certPinner = new CertificatePinner.Builder()
.add("myown_hostname", "sha256/4hw5tz+scE+TW+mlai5YipDfFWn1dqvfLG+nU7tq1V8=");

OkHttpClient.Builder builder = new OkHttpClient.Builder().certificatePinner(certPinner);
builder.addInterceptor(new Interceptor() {
	@Override
	public Response intercept(Chain chain) throws IOException {
		Request originalRequest = chain.request();
		Request.Builder builder = originalRequest.newBuilder()
				.addHeader("Content-Type", "application/json")
				.post(formBody);

		Request newRequest = builder.build();
		return chain.proceed(newRequest);
	}
});
OkHttpClient client = builder.build();
final Retrofit retrofit = new Retrofit.Builder()
                    .baseUrl("http://myown_hostname")
                    .addConverterFactory(GsonConverterFactory.create(App.getDefaultGson()))
                    .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                    .client(okHttpClient)
                    .build();
networkService = retrofit.create(NetworkService.class);

```
Here is in my presenter : 
```
final Observable<MasterDataResponse> responseObservable =
                    (Observable<MasterDataResponse>) service.getPreparedObservable(
                            service.getService().getMasterData(),
                            MasterDataResponse.class, false, false);

            mCompositeDisposable.add(responseObservable
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribeOn(Schedulers.io())
                    .subscribe(this::successMasterHandleResponse, this::errorHandleResponse));
```

Is anyone had any ideas. or any sample of implementing RxAndroid with CertificatePinner(Okhttp) ?

**Comment by JakeWharton** [comment]
This doesn't seem related to RxAndroid, unless you're implying that the error is being lost when propagated from the background thread to the main thread inside the Rx stream. I can write a test like
```java
Observable.error(throw new RuntimeException())
    .subscribeOn(io())
    .observeOn(mainThread())
    .subscribe(System.out::println, System.err::println);
```
which seems to indicate that's not the case.

I suspect your error is getting lost elsewhere. I suspect it is delivered to `errorHandleResponse` which may itself be throwing an exception causing both errors to be delivered to the uncaught exception handler (although that should crash your app).

Without some kind of test case to reproduce it's impossible to know where the problem lies. I am really confident in a few things though:
* Retrofit will forward the OkHttp exception to `onError`.
* RxJava won't lose the exception in the stream and deliver it to your handler.
* RxAndroid will correctly move the callbacks from the background thread to the main thread.

What I'm not confident in is what your code is doing in the error handler and the uncaught exception handler–both of which are outside the control of RxAndroid, RxJava, Retrofit, and OkHttp. Perhaps you can ask on the RxJava mailing list with an executable sample? It also helps to try and slim down your code. For example, if you can verify that the Retrofit-created `Observable` calls `onError` then you can replace that entire code with `Observable.error` to take both Retrofit and OkHttp out of the equation.
