### ISSUE TITLE
drain battery

### ISSUE THREAD

**Issue by fatemeh2sh** [ReactiveX/RxAndroid#428]
Hi, I use in library, is possible drain battery , because in old app is not drain battery, but when i use this rx ,battery  finish ,

i use rx with retrofit.

do you help me?

**Comment by JakeWharton** [comment]
Hi, this isn't a good place for support. This issue tracker is for bug reports and feature requests only. Moreover, this project is only RxAndroid which is a very simple wrapper around a `Handler` for RxJava. It's unlikely to cause any battery drain that otherwise wouldn't be caused by calling `Handler.post`.

For general support I would recommend using StackOverflow with the 'rx-java' tag or the RxJava mailing list which is linked in the README.

If you are convinced that RxAndroid (and not RxJava or your code's use of it) is the cause of the problem the best way to convince us is with either a test case or an executable sample project which demonstrates the issue. Without this, there's no information for us to act upon right now.
