### ISSUE TITLE
Rx Java with Gradle 5.1.1, Android Gradle 3.4

### ISSUE THREAD

**Issue by Mahesh-Chukka** [ReactiveX/RxAndroid#531]
Hi there,

I am extremely sorry about that Git glitchy, multiple issues creation. I closed all of them, except this.

Can i get some helping in resolving my dependency issues please, I am trying to add

implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
implementation 'io.reactivex.rxjava2:rxjava:2.2.8'

I am having issues in resolving these dependencies. I guess its due to my Gradle version, which is 5.1.1 and my android Gradle version 3.4.

Any help is much appreciated. Thanks.

**Comment by Mahesh523** [comment]
Hi there, 

Can i get some helping in resolving my dependency issues please, I am trying to add 

implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
implementation 'io.reactivex.rxjava2:rxjava:2.2.8'

I am having issues in resolving these dependencies. I guess its due to my Gradle version, which is 5.1.1 and my android Gradle version 3.4. 

Any help is much appreciated. Thanks.

**Comment by ZacSweers** [comment]
It's impossible to help without knowing what the "issues" are. Can you provide stacktraces, error messages, etc?

**Comment by Mahesh-Chukka** [comment]
My network was blocking the dependency download, its my problem. Apologies for this issue. I am closing it.
